<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYMgHlTF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYMgHlTF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYMgHlTF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYMgHlTF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYMgHlTF\App_KernelDevDebugContainer([
    'container.build_hash' => 'YMgHlTF',
    'container.build_id' => '3c6a91f5',
    'container.build_time' => 1741427590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYMgHlTF');
