<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ30qVKh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ30qVKh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ30qVKh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ30qVKh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ30qVKh\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q30qVKh',
    'container.build_id' => '27e235c5',
    'container.build_time' => 1741424415,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ30qVKh');
